// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkData.Data;

#nullable disable

namespace WorkData.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250905184553_Updated_declaration_model")]
    partial class Updated_declaration_model
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("WorkData.Models.Declaration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<float>("ExtraHours")
                        .HasColumnType("REAL");

                    b.Property<float>("HolidayHours")
                        .HasColumnType("REAL");

                    b.Property<float>("OrdinalHours")
                        .HasColumnType("REAL");

                    b.Property<float>("PermissionHours")
                        .HasColumnType("REAL");

                    b.Property<float>("SickHours")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Declarations");
                });
#pragma warning restore 612, 618
        }
    }
}
